import type { Metadata, Viewport } from "next";
import "./globals.css";
import { TabBar } from "@/components/TabBar";
import { Footer } from "@/components/Footer";
import { InstallHint } from "@/components/InstallHint";
import { PullToRefresh } from "@/components/PullToRefresh";
import { ServiceWorkerRegistrar } from "@/components/ServiceWorkerRegistrar";
import { ThemeController } from "@/components/ThemeController";
import { MotionProvider } from "@/components/MotionProvider";
import { Splash } from "@/components/Splash";
import { SPLASH_SEEN_KEY } from "@/lib/splash";
import { loadPriceData } from "@/lib/data";
import { Suspense } from "react";

function siteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) return process.env.NEXT_PUBLIC_SITE_URL;
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL)
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return "http://localhost:3000";
}

const SITE_URL = siteUrl();

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Stock Game — 5-Year Portfolio Showdown",
  description: "Loser pays for golf — tracked since Feb 5, 2026.",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Stock Game",
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: "Stock Game",
    title: "Stock Game — 5-Year Portfolio Showdown",
    description: "Loser pays for golf — tracked since Feb 5, 2026.",
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: "Stock Game — 5-Year Portfolio Showdown",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Stock Game — 5-Year Portfolio Showdown",
    description: "Loser pays for golf — tracked since Feb 5, 2026.",
    images: ["/og.png"],
  },
  icons: {
    icon: "/favicon.png",
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  // Dark default for first paint; ThemeController rewrites the meta tag
  // when it flips data-theme so the iOS status bar matches light/twilight.
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

// iOS home-screen launch images — without these a PWA cold launch flashes a
// blank screen. Generated by scripts/make-icons.py (public/splash/); one
// entry per (device points × pixel ratio) the group's iPhones use.
const SPLASH_SCREENS = [
  { w: 375, h: 812, r: 3 },
  { w: 390, h: 844, r: 3 },
  { w: 393, h: 852, r: 3 },
  { w: 402, h: 874, r: 3 },
  { w: 414, h: 896, r: 2 },
  { w: 428, h: 926, r: 3 },
  { w: 430, h: 932, r: 3 },
  { w: 440, h: 956, r: 3 },
];

// The footer is the only thing in the layout that needs price data. Loading
// it inside its own Suspense boundary (instead of awaiting in RootLayout)
// lets the shell — and the launch splash — stream to the phone immediately
// rather than waiting on the GitHub data read first.
async function DataFooter() {
  const data = await loadPriceData();
  const lastDate = data.tradingDates[data.tradingDates.length - 1];
  return <Footer lastDate={lastDate} generatedAt={data.generatedAt} />;
}

// Runs before first paint: once this session has seen the splash, hide it
// so reloads don't replay it (see components/Splash.tsx).
const SPLASH_SKIP_SCRIPT = `try{if(sessionStorage.getItem(${JSON.stringify(
  SPLASH_SEEN_KEY
)}))document.documentElement.dataset.splash="skip"}catch(e){}`;

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // suppressHydrationWarning: the inline splash script may set
    // data-splash on <html> before React hydrates.
    <html lang="en" className="h-full" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: SPLASH_SKIP_SCRIPT }} />
        {SPLASH_SCREENS.map(({ w, h, r }) => (
          <link
            key={`${w}x${h}@${r}`}
            rel="apple-touch-startup-image"
            media={`(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`}
            href={`/splash/splash-${w * r}x${h * r}.png`}
          />
        ))}
      </head>
      <body className="min-h-full bg-page text-ink antialiased">
        <Splash />
        <ThemeController />
        <ServiceWorkerRegistrar />
        <InstallHint />
        <PullToRefresh />
        <MotionProvider>
          <main
            className="max-w-md mx-auto pb-20"
            style={{ paddingTop: "env(safe-area-inset-top)" }}
          >
            {children}
            <Suspense fallback={null}>
              <DataFooter />
            </Suspense>
          </main>
        </MotionProvider>
        <TabBar />
      </body>
    </html>
  );
}
